config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'

  get '/team' => 'pages#team'

  get '/contact' => 'pages#contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def team
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/navbar_layout_helper.rb
module NavbarLayoutHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>17WebDev.com</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Play" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=BioRhyme" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css?family=Copse" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css?family=Quantico:700" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css?family=Dosis:700|Quantico:700" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css?family=Knewave" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
<!--    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300" rel="stylesheet"> -->
  </head>
  <body>

    <%= render 'shared/navbar' %>

    <div class="page_content <%= controller.controller_name %>">
    <%= yield %>
    </div>
    
    <%=render 'shared/footer'%>

  </body>
</html>

app/views/pages/about.html.erb
<div class="row">
	<div class="col-lg-5">
		<%= image_tag("logo.png", class: 'aboutlogo') %>
	</div>
	<div class="col-lg-7">
		<h4 id="abouttext">
			17 Web Development & Design stands on the belief of web development being an underestimated art form.<br> Each project demands extreme attention to detail from our highly dedicated developers.<br> Our team desires to make your vision come to life.<br> Contact us now to assist in forwarding your goal.
		</h4>
	</div>
</div>
<div class="row">
		<h1 class="team">Team:</h1>
		<div class="col-lg-4">
			<img  src="assets/james.jpeg" width="130px" height="130px"><h1>James Sullivan<br>Founder/Cofounder<br>Developer</h1>
		</div>
		<div class="col-lg-4">
			<img  src="assets/kyle.jpg" width="130px" height="130px"><h1>Kyle Harmon<br>Founder/Cofounder<br>Developer</h1>
		</div>
</div>

app/views/pages/contact.html.erb
<div class="container container_5">
      <div class="row row_6">
        <div class="serv_5">
          <h1 class="services_5">Contact Us!</h1>
               <br>
               <br>
          <div class="col-lg-8" align="center">
            <div class="servdis_5" >
              <img class="img-square email" src="assets/email_2.png" width="300" height="300">
              <h2>Shoot us an Email!</h2>
              <p>Send us an email with your name, company, contact info and any questions you may have! One of our certified web developers will answer you within 24 hours. We look foward to hearing from you!</p>
              <h4><a href="mailto:contact.us@17webdev.com">contact.us@17webdev.com</h4></a>
            </div>
          </div><!-- /.col-lg-8 -->
        </div><!-- /.servdis_5 -->
      </div><!-- /.row_5 -->
  </div><!-- /.container_5 -->
<br>
<br>

<!-- 
(EVENTUALLY INSTALL SENDGRIND OR MAILCHIP SO WE CAN SEND OUT MONTLY USER TRAFFIC REPORTS TO CLIENTS)

(HIDE FOR NOW)

font-family: 'Roboto', sans-serif; may go well with our other fonts for the headers

            </div>
          </div><!/.col-lg-8
         </div> --><!-- /.servdis_6 -->
      <!-- </div>/.row_6 -->
    <!-- </div>/.container_6 -->
<!-- <br>

 --> 

app/views/pages/home.html.erb
<!-- Three columns of text below the carousel -->
    <div class="container-fluid">
      <div class="row row_1">
        <div class="col-lg-12 col-lg-offset-4">
          <img class="logo-big" align="center" src="assets/tree_logo.png" height="300px" width="500px">
          <br>
          <br>
          <h1 class="company_name" align="center"> /> Web Dev </h1>
        </div>
      </div>
      <div class="row row_2" align="center">
          <h1 id="services">Services</h1>
          <br>
          <br>
          <div class="col-lg-4" align="center">
              <img class="img-square" src="assets/coding.png" width="300" height="200">
              <h2>UX/UI Design & Web Development</h2>
              <p>Our certified web developers design and build a variety of websites for our clients. We have experience in creating personal, corporate, ecommerce, educational, and financial sites. Ranging from single landing pages to websites built around entire databases, our developers truly have diverse portfolios.</p>
          </div><!-- /.col-lg-4 -->
          <div id="2" class="col-lg-4" align="center">
              <img class="img-square" src="assets/single-page-websites.jpg" width="300" height="200">
              <h2>Custom or Templated Designs</h2>
              <p>We have the experience to build fully custom or templated websites. Custom websites can be created using frameworks, plugins and API integration.</p>
          </div><!-- /.col-lg-4 -->
          <div id="3" class="col-lg-4" align="center">
              <img class="img-square" src="assets/web-design-services-page.png" width="250" height="200">
              <h2>Multi-Platform Web Development</h2>
              <p>Our team builds websites that can be scaled for every device and viewed on all platforms. </p>  
              <br>
              <br>
              <br>
          </div><!-- /.col-lg-4 -->
        <div class="row row_button" align="center">
          <div class="col-lg-4" align="center">
            <form class="additional_services" align="center">
             <button class="add_services_button" type="button">
               <h5 id="additional_services">Additional Services</h5>
             </button> 
            </form>
          </div>
      </div><!-- /.row -->
      

      <div id="row_additional" class="row row_additional" align="center">
          <h1 id="services_add">Additional Services</h1>
          <form align="center" class="close_add_services">
            <button class="close" type="button">
              <h2 align="center" id="x" class="x">X</h2>
            </button>
          </form>
          <br>
          <br>
          <div class="col-lg-9" align="center">
              <img id="handshake" class="img-square" src="assets/handshake.png" width="150" height="150">
              <h2>CTO's For Hire</h2>
              <br>
              <p> Our team can be hired as the CTO of your company or will take on individual projects outsourced by your tech team.</p>
          </div><!-- /.col-lg-9 -->
          <div class="col-lg-9" align="center">
              <img class="img-square" src="assets/web_traffic.png" width="150" height="150">
              <h2>User Traffic Tracking Analysis</h2>
              <br>
              <p> We use technology to track user traffic and demographics. We can  apply this to a website we built for you or your existing one. Depending on what type of data you choose to be displayed, we can create monthly or yearly reports using D3.js. </p>
          </div><!-- /.col-lg-9 -->
          <div class="col-lg-9" align="center">
              <img class="img-square" src="assets/research.png" width="150" height="150">
              <h2>Database Analytics</h2>
              <br>
              <p>Given the information your database acquires, we can process that information into simple statistics presented with charts and graphs using D3.js. We can provide this on a monthly or yearly basis for your company or team. </p>  
          </div><!-- /.col-lg-9 -->
          <div class="col-lg-9" align="center">
             <img class="img-square" src="assets/maintance.png" width="150" height="150">
              <h2>Monthly Website and Server Maintenance</h2>
              <br>
              <p> We will maintain all of your website needs. Whether updates are needed weekly, monthly, or yearly, we will make sure it is always live, up to date and running smoothly.</p> 
          </div><!-- /.col-lg-9 -->
      </div><!-- /.row -->

      <!-- Three columns of text below the carousel -->

      <div class="row row_3" align="center">
      <h1 class="services_2">Languages</h1>
<br>
<br>
        <div class="col-lg-2" >
          <img align="center" class="img-square" src="assets/html.png" height="150">
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-2" >
          <img align="center" class="img-square" src="assets/css.png" height="150">
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-2" >
          <img align="center" class="img-square" src="assets/javascript.png" height="150">
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-2" >
          <img align="center" class="img-square" src="assets/rails.png" height="150">
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-2" >
          <img align="center" class="img-square" src="assets/swift.png" height="150">
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-2" >
          <img id="mysql" align="center" class="img-square" src="assets/mysql.png" height="150">
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->
</div>

app/views/pages/team.html.erb
<div class="container container_3">
  <div class="row row_4">

    <div class="team_spacer"><h1>Our Team</h1></div>
<br>
<!-- <br> -->
    <div class="member">
      <div id="james" class="member_portrait"></div>
      <div class="">
        <h2 class='name'>James Sullivan</h2>
        <h2 class='position'>
          CEO/Co - CTO <br>
          Head of Operations/Lead Backend Developer
        </h2>
        <!-- p class='bio'>BIO</p> -->
        <h5 class='email'><a href="mailto:jamessullivan@17webdev.com">jamessullivan@17webdev.com</a></h5>
      </div>
    </div>

    <div class="member">
      <div id="kyle" class="member_portrait"></div>
      <div class="">
        <h2 class='name'>Kyle Harmon</h2>
        <h2 class='position'>
          Co - CTO <br>
          Head of Website Security/Lead Frontend Developer
        </h2>
        <!-- <p class='bio'>BIO</p> -->
        <h5 class='email'><a href="mailto:kyleharmon@17webdev.com">kyleharmon@17webdev.com</a></h5>
      </div>
    </div>

    <div class="member">
      <div id="eric" class="member_portrait"></div>
      <div class="">
        <h2 class='name'>Eric Sui</h2>
        <h2 class='position'>
          Co - CTO <br>
          Head of New Technologies/Lead Web Developer
        </h2>
        <!-- <p class='bio'>BIO</p> -->
        <h5 class='email'><a href="mailto:ericsui@17webdev.com">ericsui@17webdev.com</a></h5>
      </div>
    </div>
  </div>
  <br>
  <br>

  <div class="row row_5">

    <div class="team_spacer team_spacer_2" align="center"><h1>Our Mission</h1></div>

    <div class="mission_box">
      <h2>17 Wed Dev professionally builds user friendly websites so that visitors want to come back again and again. Building an effective site requires many different types of techniques, strategies and the best web resources available. When a client employs 17 Web Dev, they can expect to obtain a product that will drive customers to the site on a regular basis, while also keeping them engaged while they are there.
      <br>From making sure the site is well designed and coded to easy to navigate, we take advantage of numerous resources, tools and strategies to build a site that is efficient and well liked by our clients. </h2>
    </div>

  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="relist">
    <h4>About Us</h4>
    <ul>
      <li><%=link_to "Home", root_path%> </li>
      <li><%=link_to "Team", team_path%> </li>
      <li><%=link_to "Contact", contact_path%> </li>
    </ul>
  </div>
  <div class="relist">
    <h4>Services</h4>
    <ul>
      <li><%=link_to "CTO's For Hire"%></li>
      <li><%=link_to "UX/UI Design and Web Development"%></li>
      <li><%=link_to "Custom Or Templated Websites"%></li>
      <li><%=link_to "Multi-Platoform Development"%></li>
    </ul>
  </div>
  <div class="relist location">
    <h4>Location</h4>
    <p>
    1 Journal Square Plaza <br>
    Jersey City, NJ 07306
  </p>
  </div>

</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="true">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><img class="navlogo" src="assets/tree_logo.png"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="act"><%= link_to 'Home', root_path %></li>
        <li class="act"><%= link_to 'Team', team_path %></li>
        <li class="act"><%= link_to 'Contact', contact_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>